=== StepanovSergey/Task6/WebContent/xml/products.dtd
<!ELEMENT products (category+)>
<!ELEMENT category (subcategory+)>
<!ATTLIST category name CDATA #REQUIRED>
<!ELEMENT subcategory (product+)>
<!ATTLIST subcategory name CDATA #REQUIRED>
<!ELEMENT product (producer,model,date_of_issue,color,(not_in_stock|price))>
<!ELEMENT producer (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT date_of_issue (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT not_in_stock EMPTY>

=== StepanovSergey/Task6/WebContent/xml/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE products SYSTEM "products.dtd">
<!-- <products xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.epam.com" xs:schemaLocation="http://www.epam.com products.xsd"> -->
	<products>
	<category name="electronic">
		<subcategory name="mobile">
			<product name="mob1">
				<producer>Samsung</producer>
				<model>GS003</model>
				<date_of_issue>02-09-2012</date_of_issue>
				<color>White</color>
				<price>600</price>
			</product>
			<product name="mob2">
				<producer>Nokia</producer>
				<model>WP920</model>
				<date_of_issue>07-08-2012</date_of_issue>
				<color>Blue</color>
				<price>900</price>
			</product>
			<product name="mob3">
				<producer>Apple</producer>
				<model>IP005</model>
				<date_of_issue>05-12-2012</date_of_issue>
				<color>Black</color>
				<not_in_stock />
			</product>
		</subcategory>
		<subcategory name="laptop">
			<product name="lap1">
				<producer>HP</producer>
				<model>HP815</model>
				<date_of_issue>09-07-2011</date_of_issue>
				<color>Silver</color>
				<price>900</price>
			</product>
			<product name="lap2">
				<producer>Toshiba</producer>
				<model>SA300</model>
				<date_of_issue>09-07-2010</date_of_issue>
				<color>Red</color>
				<price>500</price>
			</product>
		</subcategory>
	</category>
	<category name="auto">
		<subcategory name="battery">
			<product name="batt1">
				<producer>Varta</producer>
				<model>VA850</model>
				<date_of_issue>15-10-2012</date_of_issue>
				<color>Silver</color>
				<price>250</price>
			</product>
			<product name="batt2">
				<producer>Bosch</producer>
				<model>BH315</model>
				<date_of_issue>07-07-2012</date_of_issue>
				<color>Black</color>
				<price>350</price>
			</product>
		</subcategory>
		<subcategory name="tires">
			<product name="tir1">
				<producer>Belshina</producer>
				<model>BY155</model>
				<date_of_issue>25-09-2012</date_of_issue>
				<color>Black</color>
				<price>80</price>
			</product>
			<product name="tir2">
				<producer>Nokian</producer>
				<model>NK150</model>
				<date_of_issue>26-08-2012</date_of_issue>
				<color>Black</color>
				<not_in_stock />
			</product>
		</subcategory>
	</category>
</products>
